version: 0.0
os: linux
files:
  - source: ./csvtodxf-service-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/csvtodxf-web
hooks:
  ApplicationStart:
    - location: scripts/startApp.sh
      runas: ubuntu